config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :teams do
    resources :people
    resources :locations
  end

  root to: 'teams#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.haml
!!
%html
  %head
    %title Locator
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/locations/_form.html.haml
= form_for @location do |f|
  - if @location.errors.any?
    #error_explanation
      %h2= "#{pluralize(@location.errors.count, "error")} prohibited this location from being saved:"
      %ul
        - @location.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/locations/edit.html.haml
%h1 Editing location

= render 'form'

= link_to 'Show', @location
\|
= link_to 'Back', locations_path

app/views/locations/index.html.haml
%h1 Listing locations

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @locations.each do |location|
      %tr
        %td= location.name
        %td= link_to 'Show', location
        %td= link_to 'Edit', edit_location_path(location)
        %td= link_to 'Destroy', location, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Location', new_location_path

app/views/locations/new.html.haml
%h1 New location

= render 'form'

= link_to 'Back', locations_path

app/views/locations/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @location.name

= link_to 'Edit', edit_location_path(@location)
\|
= link_to 'Back', locations_path

app/views/people/_form.html.haml
= form_for(person) do |f|
  - if person.errors.any?
    #error_explanation
      %h2
        = pluralize(person.errors.count, "error")
        prohibited this person from being saved:
      %ul
        - person.errors.full_messages.each do |message|
          %li= message
      <% end %>
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit %>
  

app/views/people/edit.html.haml
%h1 Editing Person

= render 'form', person: @person

= link_to 'Show', @person
|
= link_to 'Back', people_path

app/views/people/index.html.haml
%p#notice= notice

%h1 People

%table
  %thead
    %tr>
      %th Name
      %th{ colspan: '3' }
  %tbody
    - @people.each do |person|
      %tr
        %td= person.name
        %td= link_to 'Show', person
        %td= link_to 'Edit', edit_person_path(person)
        %td= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' }
%br

= link_to 'New Person', new_person_path

app/views/people/new.html.haml
%h1 New Person

= render 'form', person: @person
= link_to 'Back', people_path

app/views/people/show.html.haml
%p#notice= notice

%p
  %strong Name:
  = @person.name

= link_to 'Edit', edit_person_path(@person)
|
= link_to 'Back', people_path